Bunch of fixes

diff --git a/.local/bin/mark b/.local/bin/mark
--- a/.local/bin/mark
+++ b/.local/bin/mark
@@ -3,8 +3,14 @@
 # Script for converting markdown files to HTML
 # with github flavored format and stylesheet
 #
-#   - If no file is provided, then it checks for a README.md
-#     in the current directory and converts it
+# If no file is provided, then it checks for a README.md
+# in the current directory and converts it
+#
+#  - exit with 3 when no file was converted
+#  - exit with 4 when file provide does not exists
+
+# Exit if any command fails
+set -e
 
 md_file="$1"
 default_dir="./.markdown"
@@ -16,10 +22,11 @@ main() {
             md_file="README.md"
         else
             echo "mark: No file provided and no README detected"
-            return
+            exit 3
         fi
-    elif [ -d "$md_file" ]; then
-        echo "mark: $md_file is a directory"
+    elif [ ! -f "$md_file" ]; then
+        echo "mark: $md_file doesn't exists"
+        exit 4
     fi
 
     [ -d "$default_dir" ] || mkdir "$default_dir"
@@ -32,12 +39,15 @@ main() {
     md2html --github --output="$tmpfile" "$md_file"
 
     output_html="${default_dir}/${md_file}.html"
+    copy_path=$(realpath "$output_html")
 
     cat "$HOME/.local/bin/markdown/start-mark.html" \
         "$tmpfile" \
-        "$HOME/.local/bin/markdown/end-mark.html" > "${output_html}"
+        "$HOME/.local/bin/markdown/end-mark.html" > "${copy_path}"
 
-    echo "Created: $(realpath $output_html)"
+    echo "Created: $copy_path"
+    echo "$copy_path" | gpaste-client
+
     rm "$tmpfile"
 }
 
