refactor(script): rewrite mkven as a bash script
This also remove the fzf selection functionality as it only added more
complexity and another dependency for what should be a simple script.

diff --git a/home/bin/mkvenv b/home/bin/mkvenv
--- a/home/bin/mkvenv
+++ b/home/bin/mkvenv
@@ -1,104 +1,99 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-"""Easily create virtual enviroments using `virtualenv`, `pyenv` and `fzf`."""
+# Requires
+# - pyenv
+# - python
+# - virtualenv
 
-from __future__ import annotations
+# shellcheck disable=SC2155
 
-import argparse
-import os
-import subprocess as sp
-import sys
+# Exit on errors
+set -o errexit
+set -o nounset
+set -o pipefail
 
-GREEN = '\033[32m'
-NORMAL = '\033[0m'
+readonly default_venv=.venv
+readonly program=${0##*/}
 
+# ansi scape codes
+readonly green=$(tput setaf 2)
+readonly yellow=$(tput setaf 3)
+readonly normal=$(tput sgr0)
 
-def yesno(prompt: object) -> bool | None:
-    while True:
-        try:
-            answer = input(f'{GREEN}::{NORMAL} {prompt} [y/n] ').strip().lower()
-        except EOFError:
-            return None
-        if not answer:
-            return None
-        if answer in {'y', 'yes'}:
-            return True
-        if answer in {'n', 'no'}:
-            return False
+function error() {
+    >&2 echo "$program: $*"
+}
 
+function die() {
+    error "$@"
+    exit 1
+}
 
-def select_version() -> str | None:
-    pyenv = sp.run(['pyenv', 'versions', '--bare'], capture_output=True)
-    fzf = sp.run(
-        ['fzf', '--height=~100%', '--no-info', '--disabled', '--tac'], input=pyenv.stdout, stdout=sp.PIPE
-    )
-    version = fzf.stdout.decode(encoding='utf-8').strip()
-    if fzf.returncode != 0 or not version:
-        return None
-    return version
+function usage() {
+    cat <<EOF
+usage: ${program} [-h | venv]
 
+Easily create virtual enviroments using \`virtualenv\` and \`pyenv\`.
 
-def get_version() -> str | None:
-    try:
-        process = sp.run(['pyenv', 'local'], encoding='utf-8', capture_output=True, check=True)
-    except FileNotFoundError as e:
-        assert e.filename == 'pyenv'
-        print('==> pyenv not found', file=sys.stderr)
-        current_version = '.'.join(map(str, sys.version_info[:3]))
-        if yesno(f'Use system python ({current_version}) instead?'):
-            return current_version
-        return None
-    except sp.CalledProcessError as e:
-        assert e.stderr.startswith('pyenv: no local version')
-        version = select_version()
-        if not version:
-            return None
-        sp.run(['pyenv', 'local', version])
-        return version
-    else:
-        return process.stdout.strip()
+positional arguments:
+  venv   name for the virtual enviroment (default: ${default_venv})
 
+options:
+  -h, --help  show this help message and exit
+EOF
+}
 
-def create_vritualenv(name: str, version: str, prompt: str) -> int:
-    common_args = [name, '--prompt', prompt, '--copies']
-    try:
-        venv = sp.run(['virtualenv', *common_args, '--python', version, '--download'])
-    except FileNotFoundError as e:
-        # Fallback to standard venv if virtualenv is not present
-        assert e.filename == 'virtualenv'
-        venv = sp.run(['python', '-m', 'venv', *common_args, '--upgrade-deps'])
-    return venv.returncode
+# https://stackoverflow.com/a/3352015/22197708
+function trim() {
+    local var="$1"
+    var="${var#"${var%%[![:space:]]*}"}" # leading whitespace
+    var="${var%"${var##*[![:space:]]}"}" # trailing whitespace
+    printf '%s' "$var"
+}
 
+function mkvenv() {
+    local venv=$1 prompt version
 
-def main() -> int:
-    default_name = '.venv'
-    parser = argparse.ArgumentParser(description=__doc__)
-    parser.add_argument(
-        'venv_name',
-        default=default_name,
-        nargs='?',
-        help=f'Name for the virtual enviroment (default: {default_name})',
-    )
-    args = parser.parse_args()
+    [[ -f $venv ]] && die "venv '$venv' already exists"
 
-    venv_name: str = args.venv_name.strip()
+    # green prompt
+    prompt="\[$green\]$venv\[$normal\]"
 
-    if not venv_name:
-        parser.error(f'Empty name for virtual enviroment: {args.venv_name!r}')
+    if ! command -v virtualenv > /dev/null; then
+        python -m venv "$venv" --prompt "$prompt" --copies --upgrade-deps
+        return
+    fi
 
-    if os.path.exists(venv_name):
-        print(f'==> {venv_name!r} already exists', file=sys.stderr)
-        return 1
+    if ! command -v pyenv > /dev/null || ! pyenv local &> /dev/null; then
+        error "${yellow}WARNING${normal}: python version not set with pyenv"
+        virtualenv "$venv" --prompt "$prompt" --copies --download
+        return
+    fi
 
-    venv_version = get_version()
+    version=$(pyenv version-name)
+    virtualenv "$venv" --python "$version" --prompt "$prompt" --copies --download
+}
 
-    if not venv_version:
-        print('==> No python version selected, aborting', file=sys.stderr)
-        return 1
+function main() {
+    if [[ $# -eq 0 ]]; then
+        mkvenv "$default_venv"
+    elif [[ $# -eq 1 ]]; then
+        case "$1" in
+            -h | --help)
+                usage
+                exit 0
+                ;;
+            *)
+                local venv=$(trim "$1")
+                [[ -z $venv ]] && die 'empty venv name'
+                mkvenv "$venv"
+                ;;
+        esac
+    else
+        error 'too many arguments'
+        usage
+        exit 1
+    fi
+}
 
-    print(f'{GREEN}::{NORMAL} Creating virtual enviroment...')
-    return create_vritualenv(venv_name, venv_version, rf'\[{GREEN}\]{venv_name}\[{NORMAL}\]')
-
-
-if __name__ == '__main__':
-    sys.exit(main())
+main "$@"
